[package]
name = "plotters-ternary"
version = "0.1.0"
edition = "2024"

[dependencies]
plotters = { version = "0.3.7", default-features = false, features = [
    "bitmap_backend",
    "bitmap_encoder",
    "svg_backend",
    "ttf",
] }
plotters-backend = "0.3.7"
spline1d = { version = "0.1.0", default-features = false, features = ["alloc"] }

[dev-dependencies]
image = { version = "0.25.8", default-features = false, features = ["png"] }
proptest = "1.6"
